In [1]:
import pandas

In [3]:
df=pandas.read_csv("countries.csv")
df

       1                               Andorra  AD
0      2                  United Arab Emirates  AE
1      3                           Afghanistan  AF
2      4                   Antigua and Barbuda  AG
3      5                              Anguilla  AI
4      6                               Albania  AL
5      7                               Armenia  AM
6      8                  Netherlands Antilles  AN
7      9                                Angola  AO
8     10                            Antarctica  AQ
9     11                             Argentina  AR
10    12                        American Samoa  AS
11    13                               Austria  AT
12    14                             Australia  AU
13    15                                 Aruba  AW
14    16                         Aland Islands  AX
15    17                            Azerbaijan  AZ
16    18                Bosnia and Herzegovina  BA
17    19                              Barbados  BB
18    20                            Bangladesh  BD
19    21                               Belgium  BE
20    22                          Burkina Faso  BF
21    23                              Bulgaria  BG
22    24                               Bahrain  BH
23    25                               Burundi  BI
24    26                                 Benin  BJ
25    27                      Saint Barth√©lemy  BL
26    28                               Bermuda  BM
27    29                                Brunei  BN
28    30                               Bolivia  BO
29    31    Bonaire, Saint Eustatius and Saba   BQ
..   ...                                   ...  ..
221  223                            East Timor  TL
222  224                          Turkmenistan  TM
223  225                               Tunisia  TN
224  226                                 Tonga  TO
225  227                                Turkey  TR
226  228                   Trinidad and Tobago  TT
227  229                                Tuvalu  TV
228  230                                Taiwan  TW
229  231                              Tanzania  TZ
230  232                               Ukraine  UA
231  233                                Uganda  UG
232  234  United States Minor Outlying Islands  UM
233  235                         United States  US
234  236                               Uruguay  UY
235  237                            Uzbekistan  UZ
236  238                               Vatican  VA
237  239      Saint Vincent and the Grenadines  VC
238  240                             Venezuela  VE
239  241                British Virgin Islands  VG
240  242                   U.S. Virgin Islands  VI
241  243                               Vietnam  VN
242  244                               Vanuatu  VU
243  245                     Wallis and Futuna  WF
244  246                                 Samoa  WS
245  247                                Kosovo  XK
246  248                                 Yemen  YE
247  249                               Mayotte  YT
248  250                          South Africa  ZA
249  251                                Zambia  ZM
250  252                              Zimbabwe  ZW

[251 rows x 3 columns]